
tasks:
  - before: printf "\n[settings]\napi_key = $WAKA_TIME_API_KEY\n" > ~/.wakatime.cfg
  - init: npm install
    command: npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - github.vscode-pull-request-github
    - redhat.vscode-yaml
    - svelte.svelte-vscode
    - robole.snippets-ranger
    - bierner.color-info
    - vivaxy.vscode-conventional-commits
    - mhutchie.git-graph
    - heybourn.headwind
    - bradlc.vscode-tailwindcss
    - oderwat.indent-rainbow
    - christian-kohler.path-intellisense
    - esbenp.prettier-vscode
    - csstools.postcss
    - christian-kohler.npm-intellisense
    - vscode-icons-team.vscode-icons
    - gengjiawen.vscode-wakatime-gitpods
    - dbaeumer.vscode-eslint
    - tuto193.monokai-vibrant
    - this-fifo.natty
    - qcz.text-power-tools
